### ISSUE TITLE
Causes build errors in Android Studio

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [Arasthel/AsyncJobLibrary#1]
Adding this library to android Studio causing the following error:
    is also present at com.arasthel:asyncjob-library:1.0.0:13:9 value=(@drawable/ic_launcher)
:app:processDebugManifest
    Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:15:5 to override

**Comment by jmartinesp** [comment]
Please try again with the new source. If you used the gradle dependency version, please wait a few hours before trying again and make sure that you change the version to 1.0.3.
