### ISSUE TITLE
Execute AsyncJobs only page selected on Fragment Viewpager

### ISSUE THREAD

**Issue by emjea** [Arasthel/AsyncJobLibrary#2]
Hello i use AsyncJobs on fragment viewpager.
For example i have 3 page on viewpager.
How to execute AsyncJobs on page 2 or 3 when page only selected?
maybe like instagram apps on tab activity.

Thanks before. :smiley:

**Comment by jmartinesp** [comment]
This isn't really an issue since there is nothing wrong with the library.  If you want to do that, you probably want the pages to implement some interface son when ViewPager's OnPageChangedListener triggers, they get notified and can execute the method of that interface.

I'm closing this.
